// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Availability struct {
	ID        int64
	Traineeid sql.NullInt64
	Startdate sql.NullString
	Enddate   sql.NullString
}

type Schedule struct {
	ID        int64
	Traineeid sql.NullInt64
	Date      sql.NullString
}

type Trainee struct {
	ID      int64
	Name    sql.NullString
	Perweek sql.NullInt64
	Late    sql.NullInt64
}

type Username struct {
	Traineeid sql.NullInt64
	Username  []byte
	Password  []byte
}
